= The Dawn of Lisp

How to write `eval` and `apply` in Clojure. Code for http://2017.clojure-conj.org/[Clojure/conj 2017] presentation.

== Installing the most recent version of Leiningen

- You must have Java already installed.

- Download the Leiningen script. At the terminal type:
+
----
wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
----

- Make the script executable:
+
----
chmod +x lein
----

- Move the script to the `/usr/local/bin` directory:
+
----
sudo mv lein /usr/local/bin
----

- To run the Clojure REPL (Read-Eval-Print-Loop), type:
+
----
lein repl
----
+
Press `Ctrl-D` to quit the REPL.

== Adding plugins and dependencies to Leiningen

- Create a `profiles.clj` file in the `.lein` directory. If the `.lein` directory doesn't exist, type in your home directory:
+
----
mkdir .lein
----
+
Change to the `.lein` directory:
+
----
cd .lein
----
+
Create the `profiles.clj` file:
+
----
touch profiles.clj 
----

- Edit and save the `profiles.clj` file with the desired plugins and/or dependencies, for example:
+
[source, clojure]
----
{:user
  {:plugins      [[lein-exec "0.3.6"]]
   :dependencies [[org.clojure/math.numeric-tower "0.0.4"]
                  [org.clojure/core.logic "0.8.11"]]}}
----
+
The installation of the dependencies/plugins will occur next time you run the REPL.
+
To run a script, for example `hello_world.clj`, you can now type:
+
----
lein exec hello_world.clj
----

== Creating a Project

Type at the terminal:

----
lein new app lisp
----
